#################################################################
#  Makefile for sample of Event Pump - epump
#  Copyright (c) 2003-2020 Ke Hengzhong <kehengzhong@hotmail.com>
#  All rights reserved. See MIT LICENSE for redistribution.
#################################################################

all: 
	@(if cd echosrv;then $(MAKE) $@;fi)

clean:
	@(if cd echosrv;then $(MAKE) $@;fi)

